version: 1

# KEYS TO USES AS COLUMNS IN QUICKLOOK SUMMARY TABLES PRINTS TO STDOUT
summary-keys:
    default: ['INSTRUME', 'MJDOBS', 'DPR_TYPE', 'DPR_CATG', 'DPR_TECH', 'SEQ_ARM',
                    'EXPTIME', 'SLIT_UVB', 'SLIT_VIS', 'SLIT_NIR','INSTRUME', 'LAMP1','LAMP2','LAMP3','LAMP4','LAMP5','LAMP6','LAMP7']
    verbose: ['INSTRUME','MJDOBS', 'CDELT1', 'CDELT2', 'PSZX', 'DPR_TYPE', 'DPR_CATG', 'DPR_TECH', 'PRO_TYPE', 'PRO_CATG', 'PRO_TECH','SEQ_ARM',
                    'EXPTIME', 'NAXIS1', 'NAXIS2', 'DET_READ_SPEED', 'CONAD', 'DET_GAIN', 'RON', 'CHIP_RON', 'BUNIT', 'SLIT_UVB', 'SLIT_VIS', 'SLIT_NIR','INSTRUME', 'LAMP1', 'ABSROT']
    nodding_extras: ['NOD_JITTER_BOX','NOD_THROW','NOD_CUMULATIVE_OFFSETX','NOD_CUMULATIVE_OFFSETY']

workspace-root-dir: ./


bootstrap_dispersion_solution: False
tune-pipeline: False
PAE: False
